### ISSUE TITLE
It's summer time

### ISSUE THREAD

**Issue by jadeclan** [Nwalk957/WebLabs-4513#1]
What are you up to????

**Comment by Nwalk957** [comment]
Been doing my internship, company hired me to do a whole web / cloud
database system for them in Node.js and Angular. Hows you summer going
James?

**Comment by jadeclan** [comment]
Just got back from 8 weeks in Quebec.  Trying to remember how to turn the
computer on lol.

**Comment by Nwalk957** [comment]
Nice musta been a fun time, how was it over there? usually each computer
has a power button haha ;)

**Comment by jadeclan** [comment]
Got some sailing in and a whole bunch of cottage time.  It was great.

**Comment by Nwalk957** [comment]
Nice, im jealous, ive just been none stop coding past 2 months haha

**Comment by jadeclan** [comment]
Yeah, but I'll bet your having fun.   I can't wait to get back into it.

**Comment by Nwalk957** [comment]
Good stuff, you plan on coding more in Node and Angular?

**Comment by jadeclan** [comment]
Likely will this summer, just to play around.

**Comment by spitrola** [comment]
Hey guys, 
How is your internship going Nolan?
How was your trip to James?

**Comment by Nwalk957** [comment]
Its going pretty good learned a lot more about node and angular :)
How is your summer going Sonia what you been up to?

**Comment by spitrola** [comment]
That is awesome. You are going to be node and angular pro. Which company are you working at? My summer is going well just finished spring courses and now will relax for the remainder of the summer.

**Comment by Nwalk957** [comment]
Nice lucky you, I'm working for a company called Inova

**Comment by spitrola** [comment]
Cool, is this a 4 month internship?

**Comment by Nwalk957** [comment]
Yeppers ^.^

**Comment by spitrola** [comment]
Awesome, what does your company do?

**Comment by Nwalk957** [comment]
Company is one of the biggest veterinarian software/system providers. they
have me building them a cloud base web service for their clients to log
onto to make their data inputs more restrictive / efficient than using
their traditional excel spread sheets

**Comment by spitrola** [comment]
Nice that sounds like a lot of fun.

**Comment by Nwalk957** [comment]
A lot a freakin work to do, especially when your the only one assigned to
the project haha

**Comment by spitrola** [comment]
Haha omg that's crazy, but it's ok just take it a step at a time.

**Comment by Nwalk957** [comment]
Yea tomorrow i get to start working on build customized homePages for each
user, should be interesting :/

**Comment by spitrola** [comment]
Nice and how is that going so far?

**Comment by Nwalk957** [comment]
Not to bad, making good progress ^.^ you and James going to be in prog4
next semester?
On Jul 6, 2016 7:36 PM, "Sonia Pitrola" <notifications@github.com> wrote:

Nice and how is that going so far?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Nwalk957/WebLabs-4513/issues/1#issuecomment-230955816>,
or mute the thread
<https://github.com/notifications/unsubscribe/AP3nJvEkktLepnnwUQDMJSGKZ8cBQkrfks5qTFgfgaJpZM4JBfW9>
.

**Comment by spitrola** [comment]
Yes we will be in prog4 next semester. We are so excited haha

**Comment by spitrola** [comment]
what classes are you taking in the fall?

**Comment by Nwalk957** [comment]
I don't remember :s what so u guys plan on building for an app?
On Jul 6, 2016 8:37 PM, "Sonia Pitrola" <notifications@github.com> wrote:

what classes are you taking in the fall?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Nwalk957/WebLabs-4513/issues/1#issuecomment-230964170>,
or mute the thread
<https://github.com/notifications/unsubscribe/AP3nJsduqK50SN1COiqSWZcpNB1muekCks5qTGZ8gaJpZM4JBfW9>
.

**Comment by jadeclan** [comment]
We've got a couple ideas - top of the list is a Food Item Checker for the
food bank -- take a bar code picture, then go off and get information about
the product and recalls (if there are some).

About 10 other Food Bank related ideas.   We also started thinking about a
Math tutoring app, but we like the Food Bank one better at this point.

Any suggestions on how to tackle things?

**Comment by Nwalk957** [comment]
WIth the phone scanning idea I feel like you would need to gain access to
someonelses db or create you own and track all the details urself

**Comment by Nwalk957** [comment]
Just working, what's up?
